backend:
  image: kanchana20/argocd-backend
<<<<<<< HEAD
  tag: v2
=======
  tag: 672d8a2
>>>>>>> f53bf29b4809ba5645e06f9be66ec841771d4db1
  replicas: 2
  port: 5000
  mongoUri: mongodb://mongo:27017/argocd-login
  jwtSecret: supersecretkey123
frontend:
  image: kanchana20/argocd-frontend
  tag: 672d8a2
  replicas: 1
  port: 80
  nodePort: 30081
mongo:
  image: mongo
  tag: "6"
  replicas: 1
  port: 27017
  storage: 1Gi
