backend:
  image: kanchana20/argocd-backend
  tag: 0a6485a
  replicas: 2
  port: 5000
  mongoUri: mongodb://mongo:27017/argocd-login
  jwtSecret: supersecretkey123
frontend:
  image: kanchana20/argocd-frontend
  tag: 0a6485a
  replicas: 1
  port: 80
  nodePort: 
mongo:
  image: mongo
  tag: "6"
  replicas: 1
  port: 27017
  storage: 1Gi
