backend:
  image: kanchana20/argocd-backend
  tag: f50afc1
  replicas: 2
  port: 5000
  mongoUri: mongodb://mongo:27017/argocd-login
  jwtSecret: supersecretkey123
frontend:
  image: kanchana20/argocd-frontend
  tag: f50afc1
  replicas: 1
  port: 80
  nodePort: 30081
mongo:
  image: mongo
  tag: "6"
  replicas: 1
  port: 27017
  storage: 1Gi
