name: CI - Build and Deploy

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: kanchana20/argocd-backend:${{ steps.tag.outputs.TAG }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: kanchana20/argocd-frontend:${{ steps.tag.outputs.TAG }}
      
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          
      - name: Update image tags in helm values.yaml
        run: |
          TAG=${{ steps.tag.outputs.TAG }}
          yq e ".backend.tag = \"$TAG\"" -i helm/values.yaml
          yq e ".frontend.tag = \"$TAG\"" -i helm/values.yaml

      - name: Commit and push updated helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/values.yaml
          git commit -m "ci: update image tags to ${{ steps.tag.outputs.TAG }}"
          git push

          